### ISSUE TITLE
Extension Not Workin

### ISSUE THREAD

**Issue by spudly1987** [Motyldrogi/fansly-downloader#11]
_Has anything happened to the extension, i followed the instructions but not getting the download functionality?_

**Comment by Motyldrogi** [comment]
Are you using the newest version 2.0.3? There has been a problem last week which is already fixed

**Comment by spudly1987** [comment]
_Well let me ask, I was able to confirm it is working with my Google Chrome browser, However I do use Opera Gx as my primary browser and I know it uses the Google Chrome store, should this extension also work on the Opera Gx browser or only Google Chrome. Also as a secondary question, I know if a post has more then one photo it seems I can't download them all at one lump i have to download each one, one at a time. Is this normal?_

**Comment by osaminagano** [comment]
> i followed the instructions but not getting the download functionality?

Hi spudly,

1) Opera should work with chromium, so yes it should be work if you install the extension manually.
Can you please share with us the logs from opera if it dosen't work?

2) the download only works one at a time

**Comment by spudly1987** [comment]
> > i followed the instructions but not getting the download functionality?
> 
> Hi spudly,
> 
> 1. Opera should work with chromium, so yes it should be work if you install the extension manually.
>    Can you please share with us the logs from opera if it dosen't work?

_So, after doing some research to find the log file I found it in the directory 
C:\Users\(name)\AppData\Roaming\Opera Software\Opera GX Stable" however I have two log files. one "LOG" and one "LOG.OLD" both of which are showing no data and 0kb so unless there is another log file to share, i'm not sure what to do?_

**Comment by osaminagano** [comment]
> > > i followed the instructions but not getting the download functionality?
> > 
> > 
> > Hi spudly,
> > 
> > 1. Opera should work with chromium, so yes it should be work if you install the extension manually.
> >    Can you please share with us the logs from opera if it dosen't work?
> 
> _So, after doing some research to find the log file I found it in the directory C:\Users(name)\AppData\Roaming\Opera Software\Opera GX Stable" however I have two log files. one "LOG" and one "LOG.OLD" both of which are showing no data and 0kb so unless there is another log file to share, i'm not sure what to do?_

Hi,
To get the logs you can simply press left mouse button -> inspect -> in the console that will open you move under the "console" tab.
At this point go back to the fansly tab as well and do the download operation.
Return to the other window and you will see that the logs will have appeared (since it will error the prompt).
Left-click on any of them and do save us.
 
Before submitting the logs I would ask you to clean up the tab by pressing on the crossed out circle diff beside the word "top" in the upper left corner.

**Comment by spudly1987** [comment]
_Thank you for the information. but that's the problem though is that in the Opera GX browser the download button doesn't even show up in order for me to utilize it. The steps that I took to adding it to the browser are the same that I did with the Google Chrome browser, but even after refreshing closing out the window and reopening the "Download" button does not show up while within the Opera Gx Browser. I've attached the screen shot of where the download button should be but as you can see it's not there. I have also attached the screenshot for the details page of the extension within the Opera Gx Browser as well_



![Screenshot 2023-01-25 165706](https://user-images.githubusercontent.com/59564520/214701210-2879bd37-cb5e-4ea6-b323-980117afb699.png)

![image_2023-01-25_170212939](https://user-images.githubusercontent.com/59564520/214701525-26932682-e3d0-482a-b7ea-4ee41273580e.png)

**Comment by Motyldrogi** [comment]
@spudly1987 I just added the extension to a fresh installation of Opera GX. I have the exact same settings as in your screenshot. Somehow it works for me, so I don't really know what could be the problem here. Maybe it interferes with other extensions?
