### ISSUE TITLE
Does not download Audio files

### ISSUE THREAD

**Issue by LexisMikaya** [Motyldrogi/fansly-downloader#13]
It downloads audio as a png, and changing the file extension to mp3 doesn't make the audio work. It downloads videos just fine but not audio. Is audio a work in progress?

**Comment by Motyldrogi** [comment]
@LexisMikaya I don't use the website personally. So I didn't even know about audio files. Can you maybe find a post containing an audio file which I can access without a subscription. I will take a look at it and impelement it then.

**Comment by LexisMikaya** [comment]
[Here you go](https://fansly.com/post/472027459408109569)

**Comment by Motyldrogi** [comment]
@LexisMikaya Hey I just pushed a new update. It should now download the audio file as a mp4 file. They actually use mp4 audio instead of mp3, thats probably why it didn't work when you have renamed it to mp3. Pls let me know if it still doesn't work

**Comment by LexisMikaya** [comment]
It works now once I updated and restarted my browser. Thanks!
