### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by noonotthat** [Motyldrogi/fansly-downloader#15]
it appears fansly has updated again and the downloader no longer works.

**Comment by tallgirlsrhot** [comment]
I never update fansly.  I notice that there is thing that says "there is a new version of fansly, would you like to update".  Naturally people think something like there might be a bug fix etc.  Wrong, its there to put the screws to programs like this.  It is their way of being assholes.  However, there is a little X in the upper right of the update thing that just closes the update alert window until the next time you log into fansly.  I have been doing that, in fact brb going to try it right now.  Okay everything seems to be working for me.  Using google chrome by the way.

**Comment by noonotthat** [comment]
I don't update it anymore either (and I haven't for a long time now,) I will try again shortly and let you know

**Comment by noonotthat** [comment]
Sorry for the late response, I went and tried again today and it worked, so I must have been doing someting wrong the other day. Thank you for your quick initial response though.
