### ISSUE TITLE
download icons not showing after recent website update

### ISSUE THREAD

**Issue by alfratrople** [Motyldrogi/fansly-downloader#3]
hello, just informing you that fansly seems to have done some kind of update to their site which makes this downloader no longer function. could totally be some sort of error or mistake on my part, but it was working fine with no issues at all until a recent website update. if you knew about this already, disregard.

**Comment by Motyldrogi** [comment]
Hello, thank you for reporting 👍🏻 You were right, it had stopped working. But it is fixed now and will be updated in the chrome webstore soon.
