### ISSUE TITLE
Unable to download multiple photos in one post

### ISSUE THREAD

**Issue by spudly1987** [Motyldrogi/fansly-downloader#4]
Hi i've been using the downloader for some time now, and just today, IDK if its just me, but when you click to download multiple photos in one post you click on the first download by the like button for the post but then don't get the download icon in the upper left. i have uninstalled and reinstalled the app to no avail, even tried in incognito and still isn't working?

**Comment by PatrickMelanson** [comment]
I would just like to add that I am also experiencing the "multiple photos has no download button" issue. Single photos work fine, single videos too. But when I click the "download" button below a post with multiple pics, it opens the post up without a way to download the pics.

**Comment by spudly1987** [comment]
I am happy to hear that i'm not the only one experiencing this issue. I hope whoever works on this will see these massages and address the situaton

**Comment by Motyldrogi** [comment]
@spudly1987 @PatrickMelanson @Asthannoln @ChrisAMillar 
Hey guys, thanks for reaching out. I fixed it just now and it will soon be updated in the chrome webstore.
