### ISSUE TITLE
possible issue

### ISSUE THREAD

**Issue by alfratrople** [Motyldrogi/fansly-downloader#5]
hello again. there could be an issue with downloading multiple images in a gallery. it still works for when its just one video or image in a post, but if theres multiple in a bundle it seems not to work. if im just retarded then i sincerely apologise ;_;

**Comment by Motyldrogi** [comment]
@alfratrople I couldn't find any problems, is it still not working for you?

**Comment by alfratrople** [comment]
i double checked and for some reason i had to redownload the addon, but its working now. sorry for wasting your time '^^

**Comment by Motyldrogi** [comment]
@alfratrople no problem 😅
