### ISSUE TITLE
onDownloadClickModal not working

### ISSUE THREAD

**Issue by TheNyneR** [Motyldrogi/fansly-downloader#6]
Hey there.
Just tried downloading something and got:
```
Uncaught TypeError: Cannot read properties of undefined (reading '2')
    at HTMLDivElement.onDownloadClickModal (content.js:formatted:38:36)
```

The line in question:

```
const downloadLink = event.path[2].querySelector(".video")?.src || event.path[2].querySelectorAll(".image")[1]?.src || event.path[2].querySelectorAll(".image")[0]?.src;
```

I tried debugging a little and the `onDownloadClickModal` method seems to get a `PointerEvent` which does not include a `path` attribute.

Browser is ungoogled chromium.

**Comment by Motyldrogi** [comment]
@TheNyneR 

Hey, idk why ungoogled chromium somehow uses another event for clicks as the normal chrome. But you need to replace every occurence of the **event.path[2]** with **event.target.parentNode** in the file **content.js**

Like this:
**event.target.parentNode.querySelector[...]**

At lines 62, 63, 64 and 156. I just tested it really quick, but it seemed like everything was working.
