### ISSUE TITLE
Downloader no longer works needs updating

### ISSUE THREAD

**Issue by tallgirlsrhot** [Motyldrogi/fansly-downloader#8]
I think Fansly updated their system and the download button no longer works.  I tried on a fresh install of chrome and still no luck.

**Comment by Motyldrogi** [comment]
Hey, for me everything works fine. So it's hard to find the problem

I guess you can help me if you tell me what you have tried to download, is the download button still visible etc.

**Comment by Painstarz** [comment]
![ERRORCode](https://user-images.githubusercontent.com/118805389/203268595-fe68d1e1-a24a-44f9-aa10-c9200f658dec.png)
This is the error that Chrome is showing when i try to use it. button still appears but when i click on it nothing happens.

**Comment by Motyldrogi** [comment]
@Painstarz thank you, will look into it soon

**Comment by Painstarz** [comment]
Hi there, any update on fixing the error?

**Comment by osaminagano** [comment]
Hi,
I solve the issue.
Please open content.js and modify "onDownloadClickModal" method with this code:

![fixButtonDownload](https://user-images.githubusercontent.com/122574926/212196759-eb152171-3a63-49ac-9365-6031be9e33bc.png)

Save and reinstall the extension.

Notes:
The main problem is "event.path" because is pretty common browsers changes something in this old method, so i use event.composedPath() for take urls and add a condition to every if exist or not.

**Comment by noonotthat** [comment]
Is there any chance you could she your modified content.js file? I tried doing this but it still isn't working and I want to make sure I didn't do something wrong.

**Comment by osaminagano** [comment]
> @osaminagano Is there any chance you could she your modified content.js file? I tried doing this but it still isn't working and I want to make sure I didn't do something wrong.

i create i new repository [https://github.com/osaminagano/fansly-downloader-bugfix-v1](url), unfortunaly idk how use github so i can't create a pull request

**Comment by osaminagano** [comment]
> @osaminagano Is there any chance you could she your modified content.js file? I tried doing this but it still isn't working and I want to make sure I didn't do something wrong.

Just remember to delete your extension and install the new one with the fix.
Please tell me if you have others problems.

**Comment by noonotthat** [comment]
@osaminagano Thank you so much! it worked, your the man!

**Comment by Monkeymen1** [comment]
@osaminagano I tried the fix as you mentioned, but i keep having errors (I'm probably messing it up somewhere). Your link to the modified content.js file also doesn't seem to work anymore, could you post that again?  Thanks for the help.

**Comment by osaminagano** [comment]
> our link to the modified content.js file also doesn't seem to work anymore,

Hi,

I just try and it works. Can you please give me google logs?
Or at least check in logs what is the error

**Comment by BobBoh1** [comment]
@osaminagano I'm actually having the same problem as @Monkeymen1.
I tryed fixing it manually without any results and the new link you gave us doesn't work...
Could you please share it again?

**Comment by Monkeymen1** [comment]
Hi,
![image](https://user-images.githubusercontent.com/122705993/212503979-2daa7e00-e182-43ce-b15a-d6c3d729faf1.png)
this is the error i get.

And when i click on the link for the file it sais "No results matched your search."

The button does not show up on media.

**Comment by noonotthat** [comment]
Just go to his profile, he has the entire thing there to download. That's how I got it.

**Comment by Monkeymen1** [comment]
> Just go to his profile, he has the entire thing there to download. That's how I got it.

Tried that already, it's not on there. 7 repositories show up, none of them are bugfix-v1.

**Comment by BobBoh1** [comment]
> > Just go to his profile, he has the entire thing there to download. That's how I got it.
> 
> Tried that already, it's not on there. 7 repositories show up, none of them are bugfix-v1.

Same here

**Comment by noonotthat** [comment]
![Screen Shot 2023-01-14 at 7 34 51 PM](https://user-images.githubusercontent.com/122693046/212505110-b97e4a0e-2932-4896-ae7d-3d4f76ab8b32.png)

**Comment by BobBoh1** [comment]
> ![Screen Shot 2023-01-14 at 7 34 51 PM](https://user-images.githubusercontent.com/122693046/212505110-b97e4a0e-2932-4896-ae7d-3d4f76ab8b32.png)

I got that, is not fixing anythi for me... Am I suppsed to manually adjust it?

**Comment by BobBoh1** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading '2')

This is the error I got in 63

**Comment by Motyldrogi** [comment]
Hello Guys, @DeltaBoss has created a update containing the fix from @osaminagano Thank you!

You can just download the extension as usual now and it should be fixed. You can just replace the files in the extensions folder or better, to make sure everything works, just remove the extension delete the whole folder and reinstall

**Comment by Waddelo** [comment]
![imdum](https://user-images.githubusercontent.com/122657071/212508477-dcd4a9fa-44d8-489c-a111-ddfaa12d5b13.png)
No idea how I managed to get an error with the fix. It seems to only affect the post download button, opening the images and videos one by one and using the download button in the upper-left corner works.

**Comment by Motyldrogi** [comment]
@Waddelo I know what's the problem, i will fix it

**Comment by Motyldrogi** [comment]
@Waddelo Should be fixed, can you pls try again

**Comment by Waddelo** [comment]
@Motyldrogi Now the post download button downloads photos and videos in single file posts. For posts with multiple files it just opens the full view and the download button in the corner is purple instead of white.

**Comment by Motyldrogi** [comment]
@Waddelo So it works i guess, in multi file posts it is supposed to open it, because it is technically not possible to download all the files in the highest quality. You have to download each individually.

**Comment by Waddelo** [comment]
@Motyldrogi  I thought I remembered it doing that before, my mistake. Cheers then it's fixed!

**Comment by Motyldrogi** [comment]
@Waddelo There is also a fansly scraper, which can download all the files from a user at once. They use an other approach as me, so there it's possible. It's a bit more complicated to install but it is described in the repository. https://github.com/Avnsx/fansly

**Comment by osaminagano** [comment]
I'll delete my repository since this one is update.
Thank you so much guys for the collaboration!
Is always great when people work togheter for a same goal haha
