### ISSUE TITLE
The downloader stopped working

### ISSUE THREAD

**Issue by BobBoh1** [Motyldrogi/fansly-downloader#9]

**Comment by Waddelo** [comment]
Same here. Chrome says 

Uncaught TypeError: Cannot read properties of undefined (reading '2')

Stack Trace
content.js:156 (anonymous function) 

const feedItemContent = event.path[2].closest(".feed-item-content");

**Comment by osaminagano** [comment]
> Same here. Chrome says
> 
> Uncaught TypeError: Cannot read properties of undefined (reading '2')
> 
> Stack Trace content.js:156 (anonymous function)
> 
> const feedItemContent = event.path[2].closest(".feed-item-content");

Hi, in theard <https://github.com/Motyldrogi/fansly-downloader/issues/8> i solve the issue.
please download visual code and do manual the modify.
